# Generated by Django 2.0 on 2017-12-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userloginactivity',
            old_name='login_email',
            new_name='login_username',
        ),
    ]
